#Application properties
server:
  port: 8084
  
spring:
  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto:  update
    show-sql: true
    
  application:
     name: CO-API
     
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysqldb:3306/arapidb
    username: root
    password: root
    
#  boot:
#    admin:
#      client:
#          url: http://localhost:1111/
          
 #Includes all acturators. 
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
 #AWS Credintials :
 #Access Key  : AKIAWXDCWAD3P3IWBDJW
 # Secreate Key : zhq4gMUVvqiF6sDdcxByPxDP0LbySIA8zJMsEyly  

#cloud:
#  aws:
#    credentials:
#      access-key: AKIAWXDCWAD3FUQLMLIP
#      secret-key: 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
#    region:
#      static: ap-south-1
#    stack:
#      auto: false
      
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
app:          
 messages:          
  welcomeMsg: Welcome To Mukesh IT !!!
  greetMsg:   Have A Good Day !!! 

 